name: Destroy Infra
on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_chave_ssh: ${{ github.ref == 'refs/heads/production' && secrets.CHAVE_PROD || secrets.CHAVE_STAG }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      
      - name: Terraform Init e Workspace
        run: |
          echo "${{ secrets.BACKEND_CONFIG }}" > backend.hcl
          terraform init -backend-config="backend.hcl"
          WORKSPACE=${{ github.ref == 'refs/heads/production' && 'prod' || 'stag' }}
          terraform workspace select $WORKSPACE
          
      - name: Terraform Destroy
        run: terraform destroy -auto-approve