name: Destroy Infra
on:
  workflow_dispatch:

permissions:
  id-token: write # Isso permite que a action solicite o token OIDC
  contents: read  # Isso permite que a action baixe o seu código

jobs:

  codevalidate:
    name: "Verifica o código Terraform"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init -backend=false
      - run: terraform validate

  destroy:
    runs-on: ubuntu-latest
    needs: [codevalidate]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Criar arquivo de backend
        run: |
          cat <<EOF > backend-config.tfvars
          ${{ secrets.BACKEND_CONFIG }}
          EOF

      - name: Terraform Init e Workspace
        run: 
          terraform init -backend-config="backend-config.tfvars"
 
      - name: Selecionar Workspace Adaptável
        run:
          terraform workspace select stag || terraform workspace new stag
          
      - name: Terraform Destroy
        run: terraform destroy -auto-approve