name: Destroy Infra
on:
  workflow_dispatch:

permissions:
  id-token: write # Isso permite que a action solicite o token OIDC
  contents: read  # Isso permite que a action baixe o seu código

jobs:

  codevalidate:
    name: "Verifica o código Terraform"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init -backend=false
      - run: terraform validate

  destroy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_chave_ssh: ${{ github.ref == 'refs/heads/production' && secrets.CHAVE_PROD || secrets.CHAVE_STAG }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      
      - name: Terraform Init e Workspace
        run: |
          echo "${{ secrets.BACKEND_CONFIG }}" > backend.hcl
          terraform init -backend-config="backend.hcl"
          WORKSPACE=${{ github.ref == 'refs/heads/production' && 'prod' || 'stag' }}
          terraform workspace select $WORKSPACE
          
      - name: Terraform Destroy
        run: terraform destroy -auto-approve