name: Deploy EC2
run-name: ${{ github.actor }} iniciou o deploy

on:
  push:
    branches:
      - production
      - staging

permissions:
  id-token: write # Isso permite que a action solicite o token OIDC
  contents: read  # Isso permite que a action baixe o seu código

jobs:
  # 1. Validação do código
  codevalidate:
    name: "Verifica o código Terraform"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init -backend=false
      - run: terraform validate

  # 2. Verificação de Segurança
  security_scan:
    name: "Análise de Segurança (tfsec)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        
      - name: Rodar tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true

  # 3. Planejamento da Infraestrutura

  infraestrutura:
    runs-on: ubuntu-latest
    needs: [codevalidate, security_scan]
    env:
      TF_VAR_chave_ssh: ${{ github.ref == 'refs/heads/production' && secrets.CHAVE_PROD || secrets.CHAVE_STAG }}
      TF_VAR_bloco_ips_liberados: ${{ secrets.IPS_PERMITIDOS }}
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Criar arquivo de backend
        run: |
          cat <<EOF > backend-config.tfvars
          ${{ secrets.BACKEND_CONFIG }}
          EOF

      - name: Terraform Init
        run: terraform init -backend-config="backend-config.tfvars"

      - name: Selecionar Workspace
        run: |
          # Se a branch for production, usa o workspace 'prod'. Se não, usa 'stag'.
          WORKSPACE=${{ github.ref == 'refs/heads/production' && 'prod' || 'stag' }}
          
          # Tenta selecionar o workspace. Se não existir, ele cria.
          terraform workspace select $WORKSPACE || terraform workspace new $WORKSPACE

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
